title:            Mike Plummer
description:      Mike Plummer's software development cogitation.
disqus_shortname:
reading_time:     false
words_per_minute: 200

# Uncomment for deployment on GitHub
url: https://mike-plummer.github.io
# Uncomment for running locally
# url: http://localhost:4000

# Owner/author information
owner:
  name:           Mike Plummer
  avatar:         headshot.png
  bio:            "Full-stack developer in the heart of flyover country."
  email:          mike.plummer@objectpartners.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: plummer_mike
  facebook:
  github: mike-plummer
  stackexchange:
  linkedin: plummermikej
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-70902651-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Chicago
future:      true
highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - rouge
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 3

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  syntax_highlighter: :rogue,

  syntax_highlighter_opts:
    line_numbers: nil
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE.md", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", examples]
